spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/apt
    url: jdbc:mariadb://172.17.0.2:3307/apt
#    url: jdbc:mariadb://172.17.0.2:3306/apt
    username: myHome
    password: admin1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  #  port: 9080
  port: 8080

external:
  api:
    molit:
      serviceKey: "=GIzL%2BzqBUKfyHh3o%2F38ufLPiq5P%2FReUOx6NCLFEcP7rqQei%2FPIM3QbUw3rLU1gYOQfdeIREA1cLZF7lRIP5zTg%3D%3D"
      kakaoServiceKey: "//dapi.kakao.com/v2/maps/sdk.js?appkey=410b3a83564f0bac127be038fded443b&libraries=services"



#external:
#  api:
#    molit:
#      serviceKey: "actual-service-key"
#      kakaoServiceKey: "actual-kakao-service-key"






  # \uBA54\uC2DC\uC9C0 \uD30C\uC77C \uC124\uC815 \uC608\uC2DC (\uD544\uC694\uC5D0 \uB530\uB77C \uC8FC\uC11D \uD574\uC81C)
  # messages:
  #   basename: messages,errors

  # \uD30C\uC77C \uC5C5\uB85C\uB4DC \uAD00\uB828 \uC124\uC815 (\uD544\uC694\uC5D0 \uB530\uB77C \uC8FC\uC11D \uD574\uC81C)
  # servlet:
  #   multipart:
  #     max-file-size: 5MB
  #     max-request-size: 50MB

# \uC11C\uBC84 \uC124\uC815



  # \uC138\uC158 \uC124\uC815 \uC608\uC2DC (\uD544\uC694\uC5D0 \uB530\uB77C \uC8FC\uC11D \uD574\uC81C)
  # servlet:
  #   session:
  #     tracking-modes: cookie
  #     timeout: 1800 # 30\uBD84

# \uB85C\uAE45 \uC124\uC815 \uC608\uC2DC (\uD544\uC694\uC5D0 \uB530\uB77C \uC8FC\uC11D \uD574\uC81C)
# logging:
#   level:
#     org:
#       apache:
#         coyote:
#           http11: debug

# \uCCA8\uBD80\uD30C\uC77C \uC800\uC7A5 \uACBD\uB85C \uC124\uC815 (\uD544\uC694\uC5D0 \uB530\uB77C \uC8FC\uC11D \uD574\uC81C)
# attach:
#   root_dir: C:/attach/

